import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";

import "./globals.css";
import { ShiftingDropDown } from "@/components/ShiftingDropDown";
import Contact from "@/components/Contact";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={cn(
          "bg-background font-sans flex flex-col justify-between items-center h-full",
          fontSans.variable
        )}
      >
        {/* Shifting Dropdown */}
        <header className="w-full">
          <ShiftingDropDown />
        </header>

        {/* Main content */}
        <main className="flex-grow w-full flex justify-center items-center">
          {children}
        </main>

        {/* Contact section at the bottom */}
        <footer className="w-full">
          <Contact />
        </footer>
      </body>
    </html>
  );
}
